version: "3.8"
services:
  dbt_db_service:
    image: postgres:14.1
    environment:   # Set up postgres database name and password
      POSTGRES_PASSWORD: pssd
      POSTGRES_DB: dbtdb
      POSTGRES_USER: dbtuser
    ports:    # Set up ports exposed for other containers to connect to
      - 5433:5432
    networks:
      - app-tier
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    container_name: dbt_db_container

networks:
  app-tier:
    driver: bridge
